/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zowe_sample_apiservice_hello_NativeGreeting */

#ifndef _Included_org_zowe_sample_apiservice_hello_NativeGreeting
#define _Included_org_zowe_sample_apiservice_hello_NativeGreeting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zowe_sample_apiservice_hello_NativeGreeting
 * Method:    wto
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zowe_sample_apiservice_hello_NativeGreeting_wto
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
