/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zowe_sample_apiservice_hello_Wto */

#ifndef _Included_org_zowe_sample_apiservice_hello_Wto
#define _Included_org_zowe_sample_apiservice_hello_Wto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zowe_sample_apiservice_hello_Wto
 * Method:    wto
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zowe_sample_apiservice_hello_Wto_wto
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
