# Configuration for running the locally on your workstation
# It overrides service defaults provided in src/main/resources/application.yml

spring.profiles.active: https,diag

logging:
    level:
        org.zowe.commons.zos.security: DEBUG

server:
    address: 0.0.0.0
    port: 10080
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: config/local/keystore.p12                                 # Gradle
#       keyStore: zowe-rest-api-sample-spring/config/local/keystore.p12     # IntelliJ
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: config/local/truststore.p12                              # Gradle
#       trustStore: zowe-rest-api-sample-spring/config/local/truststore.p12  # IntelliJ
        trustStorePassword: password
        trustStoreType: PKCS12

apiml:
    enabled: false
    service:
        serviceId: zowesample
        hostname: localhost
        ipAddress: 127.0.0.1
        discoveryServiceUrls:
            - https://localhost:10011/eureka
