spring:
    main:
        bannerMode: "off"
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false

logging:
    level:
        ROOT: INFO
        com.netflix: WARN
        com.netflix.config: ERROR
        com.netflix.discovery: ERROR
        com.netflix.discovery.DiscoveryClient: OFF
        com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient: OFF
        org.apache.catalina: WARN
        org.apache.coyote: WARN
        org.springframework: WARN
        org.springframework.boot.web.embedded: INFO
        springfox.documentation: WARN
        com.ca.mfaas.eurekaservice.client.impl: WARN

server:
    port: 10080
    ssl:
        verifySslCertificatesOfServices: true
        enabled: false
        protocol: TLSv1.2
        enabledProtocols: TLSv1.2
        ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384

springfox.documentation.swagger.v2.path: /apiDocs/v2

zowe.commons.security.saf:
    serviceResourceClass: "ZOWE"
    serviceResourceNamePrefix: "SAMPLE."

zowe.sample.authentication: Press **Authorize** and use `zowe` as the username and `zowe` as the password

apiml:
    service:
        # Following values are default values that can be changed by user:
        serviceId: zowesample
        title: Zowe Sample API Service
        description: Sample Spring Boot API service that provides REST API
        catalogUiTile:
            id: sample
            title: Sample API Services
            description: Sample API services to demonstrate exposing a REST API service in the Zowe ecosystem
            version: 1.0.0

        # Following values are provided by the developer:
        scheme: http
        baseUrl: ${apiml.service.scheme}://${apiml.service.hostname}:${server.port}/
        homePageRelativeUrl:
        statusPageRelativeUrl: actuator/info
        healthCheckRelativeUrl: actuator/health
        routes:
            - gatewayUrl: api/v1
              serviceUrl: /api/v1
        apiInfo:
            - apiId: org.zowe.sample.api
              gatewayUrl: api/v1
              version: 1.0.0
              title: Zowe Sample REST API
              description: Sample Spring Boot REST API for Zowe. ${zowe.sample.authentication}
              swaggerUrl: ${apiml.service.scheme}://${apiml.service.hostname}:${server.port}/api/v1/apiDocs

---
spring:
    profiles: https

apiml:
    service:
        scheme: https

server:
    ssl:
        enabled: true

---
spring:
    profiles: debug


logging:
    level:
        ROOT: INFO
        org.zowe.sample.apiservice: DEBUG
        org.springframework: INFO
        org.apache.catalina: INFO
        org.apache.juli.logging: INFO
        com.netflix: INFO
        springfox.documentation: INFO
        com.ca.mfaas.eurekaservice.client.impl: INFO

---
spring:
    profiles: diag

management:
    endpoints:
        web:
            exposure:
                include: "*"

---
spring:
    profiles: zos

zowe.sample.authentication: Press **Authorize** and use your mainframe credentials
